### ISSUE TITLE
the package seems not work 

### ISSUE THREAD

**Issue by mauimoana** [DataForScience/epidemik#3]
Hi, it seems not work in my computer. Even import the package do not work. 
![image](https://github.com/user-attachments/assets/3c066d3d-bb7d-4f9c-82a7-25fd5f500b6b)

**Comment by bmtgoncalves** [comment]
Hi Mauimoana,

Thank you for reaching out. I'm happy to take a look. Can you provide more details on your setup? Also, please share the code of "untitled4.py" and/or a minimalistic code example that shows the problem. 

Best,

Bruno

**Comment by mauimoana** [comment]
Hi Bruno,

Thank you for your relpy. I didn't add any further code , just import the package would initiator the error. Another thing worth mention is that the install procedure come up a error in the first try, and then figure out by itself with my second try. Below is the snapshot.
![image](https://github.com/user-attachments/assets/b93eea7f-4bd4-48f1-b808-af54ee879646)

Best,
Mauimoana

**Comment by mauimoana** [comment]
Hi, the problem is in my own Anaconda package. Sorry for bothering you.

**Comment by bmtgoncalves** [comment]
No problem. Always happy to help!
